name: velocity_transit
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.1

dependencies:
  cloud_firestore: ^6.1.0
  firebase_auth: ^6.1.1
  firebase_core: ^4.1.0
  firebase_messaging: ^16.0.1
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.2
  flutter_map: ^8.2.2
  flutter_local_notifications: ^19.4.0
  flutter_polyline_points: ^3.1.0
  flutter_riverpod: ^3.3.1
  geocoding: ^4.0.0
  geolocator: ^14.0.2
  google_fonts: ^8.0.2
  google_maps_flutter: ^2.16.0
  google_sign_in: ^6.3.0
  http: ^1.6.0
  latlong2: ^0.9.1
  path_drawing: ^1.0.1
  permission_handler: ^12.0.1
  shared_preferences: ^2.5.3
  shimmer: ^3.0.0
  socket_io_client: ^3.1.2
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/google_g_logo.png
    - assets/logo.png
    - assets/logoanimation.gif
    - assets/mobileauthbg.png

flutter_launcher_icons:
  android: true
  ios: true
  min_sdk_android: 21
  adaptive_icon_background: "#05070D"
  adaptive_icon_foreground: "assets/logo.png"
  windows:
    generate: true
    image_path: "assets/logo.png"
    icon_size: 256
  image_path: "assets/logo.png"
